module.exports = [
  { name: 'Internal Subdomain', pattern: '([a-z0-9]+[.]*supersecretinternal[.]com)' },
  { name: 'Slack Token', pattern: '(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})' },
  { name: 'RSA private key', pattern: '-----BEGIN RSA PRIVATE KEY-----' },
  { name: 'SSH (OPENSSH) private key', pattern: '-----BEGIN OPENSSH PRIVATE KEY-----' },
  { name: 'SSH (DSA) private key', pattern: '-----BEGIN DSA PRIVATE KEY-----' },
  { name: 'SSH (EC) private key', pattern: '-----BEGIN EC PRIVATE KEY-----' },
  { name: 'PGP private key block', pattern: '-----BEGIN PGP PRIVATE KEY BLOCK-----' },
  { name: 'Facebook Oauth', pattern: '[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*[\'|"][0-9a-f]{32}[\'|"]' },
  { name: 'Twitter Oauth', pattern: '[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[\'|"][0-9a-zA-Z]{35,44}[\'|"]' },
  { name: 'GitHub', pattern: '[g|G][i|I][t|T][h|H][u|U][b|B].*[[\'|"]0-9a-zA-Z]{35,40}[\'|"]' },
  { name: 'Google Oauth', pattern: '("client_secret":"[a-zA-Z0-9-_]{24}")' },
  //{ name: 'AWS API Key', pattern: 'AKIA[0-9A-Z]{16}' },
  { name: 'Heroku API Key', pattern: '[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}' },
  { name: 'Generic Secret', pattern: '[s|S][e|E][c|C][r|R][e|E][t|T].*[\'|"][0-9a-zA-Z]{32,45}[\'|"]' },
  { name: 'Maestro Card', pattern: '^(5018|5020|5038|6304|6759|6761|6763)[0-9]{8,15}$' },
  { name: 'Master Card', pattern: '^5[1-5][0-9]{14}$' },
  { name: 'Amex Card', pattern: '^3[47][0-9]{13}$' },
  { name: 'BCGlobal', pattern: '^(6541|6556)[0-9]{12}$' },
  { name: 'Carte Blanche Card', pattern: '^389[0-9]{11}$' },
  { name: 'Insta Payment Card', pattern: '^63[7-9][0-9]{13}$' },
  { name: 'Diners Club Card', pattern: '[s|S][e|E][c|C][r|R][e|E][t|T]$' },
  { name: 'Visa', pattern: '^4[0-9]{6,}$' },
  //{ name: 'SSN', pattern: '\d{3}-\d{2}-\d{4}' },
  // { name: 'SSN', pattern: '(?!999-99-9999)(\d{3}-\d{2}-\d{4})' },
  { name: 'RSA Token', pattern: '^(ssh-[a-z]{3}) ([0-9]{3,4}) ([0-9a-f]{2}:){15}[0-9a-f]{2}$' },
  { name: 'SSH RSA', pattern: 'AAAA[0-9A-Za-z+/]+[=]{0,3} ([^@]+@[^@]+)' },
  { name: 'RSA Public Key', pattern: '^-----BEGIN PUBLIC KEY-----(.*)-----END PUBLIC KEY-----/s' },
  { name: 'Certificate key', pattern: '-----BEGIN CERTIFICATE-----' },
  { name: 'Base58 Key', pattern: '^5([1-9A-Za-z][^OIl]){20,50}' },

  // Passwords
  { name: 'PasswordString1', pattern: '(?!password=ENC)(password=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString2', pattern: '(?!password =ENC)(password =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString3', pattern: '(?!password= ENC)(password= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString4', pattern: '(?!password = ENC)(password = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString5', pattern: '(?!pwd=ENC)(pwd=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString6', pattern: '(?!pwd= ENC)(pwd= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString7', pattern: '(?!pwd =ENC)(pwd =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString8', pattern: '(?!pwd = ENC)(pwd = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString9', pattern: '(?!passwd=ENC)(passwd=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString10', pattern: '(?!passwd= ENC)(passwd= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString11', pattern: '(?!passwd =ENC)(passwd =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString12', pattern: '(?!passwd = ENC)(passwd = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString13', pattern: '(?!Password=ENC)(Password=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString14', pattern: '(?!Password =ENC)(Password =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString15', pattern: '(?!Password= ENC)(Password= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString16', pattern: '(?!Password = ENC)(Password = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString17', pattern: '(?!Pwd=ENC)(Pwd=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString18', pattern: '(?!Pwd= ENC)(Pwd= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString19', pattern: '(?!Pwd =ENC)(Pwd =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString20', pattern: '(?!Pwd = ENC)(Pwd = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString21', pattern: '(?!Passwd=ENC)(Passwd=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString22', pattern: '(?!Passwd= ENC)(Passwd= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString23', pattern: '(?!Passwd =ENC)(Passwd =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString24', pattern: '(?!Passwd = ENC)(Passwd = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString25', pattern: '(?!PASSWORD=ENC)(PASSWORD=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString26', pattern: '(?!PASSWORD =ENC)(PASSWORD =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString27', pattern: '(?!PASSWORD= ENC)(PASSWORD= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'PasswordString28', pattern: '(?!PASSWORD = ENC)(PASSWORD = [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'ClientSecretString1', pattern: '(?!client_secret=ENC)(client_secret=[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'ClientSecretString2', pattern: '(?!client_secret =ENC)(client_secret =[!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'ClientSecretString3', pattern: '(?!client_secret= ENC)(client_secret= [!@#%^&*()_+=a-zA-Z0-9]+)$' },
  { name: 'ClientSecretString4', pattern: '(?!client_secret = ENC)(client_secret = [!@#%^&*()_+=a-zA-Z0-9]+)$' },

  // Valid `grep` pattern
  { name: 'ssn', pattern: '"[0-9]{3}-[0-9]{2}-[0-9]{4}"' }
]
